siteTitle="Клиника красоты Знак Качества"
linkPrefix = "/lasertime"

fixedPhone = 89055881313
mobilePhone = 79858888297

leftMenuItems = [
    ["/actions/", "Акции"],
    ["/doctors/", "Врачи"],
    ["/services/", "Услуги"],
]

rightMenuItems = [
    ["/prices/", "Цены"],
    ["/articles/", "Статьи"],
    ["/contacts/", "Контакты"]
]