siteTitle="Lasertime Клиника"
linkPrefix = "/lasertime"

fixedPhone = 84991234567
mobilePhone = 89055881313

leftMenuItems = [
    ["/news/", "Новости"],
    ["/doctors/", "Врачи"],
    ["/services/", "Услуги"],
]

rightMenuItems = [
    ["/prices/", "Цены"],
    ["/articles/", "Статьи"],
    ["/contacts/", "Контакты"]
]