siteTitle="Клиника красоты Знак Качества. Лазерная косметология в Москве."
linkPrefix = "/lasertime"

fixedPhone = 89055881313
mobilePhone = 89055881313

leftMenuItems = [
    ["/actions/", "Акции"],
    ["/doctors/", "Врачи"],
    ["/services/", "Услуги"],
]

rightMenuItems = [
    ["/prices/", "Цены"],
    ["/articles/", "Статьи"],
    ["/contacts/", "Контакты"]
]